### ISSUE TITLE
Laplacian map

### ISSUE THREAD

**Issue by sczhou** [xrenaa/Deblur-by-Fitting#4]
Hi Xuanchi,

Could you please share the code for computing the Laplacian map for my reference?  Many thanks!

Best

**Comment by xrenaa** [comment]
Hi,

This is quiet simple in our code:

gray = cv2.cvtColor(gt_patch[0,:,:,:]*255, cv2.COLOR_RGB2GRAY)
variance = cv2.Laplacian(gray, cv2.CV_32F).var()

**Comment by sczhou** [comment]
Got it. Thanks!
